/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Tokens from "./erc20tokens";
export type { erc20Tokens };
import type * as nfts from "./nfts";
export type { nfts };
export type { Box } from "./Box";
